PLUGIN_NAME=		opn-snapshot
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Snapshot management tool
PLUGIN_DEPENDS=		opn-snapshot
PLUGIN_MAINTAINER=	corvettecole@gmail.com

.include "../../Mk/plugins.mk"
